// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYs453Ow-hX4Ql7sR4yQwIz1WWVN9sdc4',
    appId: '1:732384950609:android:6c14ea2714ada1af18fb70',
    messagingSenderId: '732384950609',
    projectId: 'evently-d9350',
    storageBucket: 'evently-d9350.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUnjuedlEC6hB8N63YCFIqzUI2IEwrgI',
    appId: '1:732384950609:ios:876db74b0b159a1d18fb70',
    messagingSenderId: '732384950609',
    projectId: 'evently-d9350',
    storageBucket: 'evently-d9350.firebasestorage.app',
    iosBundleId: 'com.example.smartSalary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsat4r6rBymZrFX4fUTaWrPygGeLu8UsU',
    appId: '1:732384950609:web:b2bcb6f35c181f6418fb70',
    messagingSenderId: '732384950609',
    projectId: 'evently-d9350',
    authDomain: 'evently-d9350.firebaseapp.com',
    storageBucket: 'evently-d9350.firebasestorage.app',
  );
}
